name: build and push container image

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: true
      arch:
        type: string
        required: true
      registry:
        type: string
        required: true
      context-directory:
        description: context directory
        type: string
        required: true
      build-cache-name:
        type: string
        required: true
      labels:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate cache scope
        id: generate-cache-scope
        run: echo "cache-scope=${{ github.ref_name }}-${{ inputs.arch }}" | sed 's|/|-|g' | tee -a "$GITHUB_OUTPUT"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.context-directory }}
          platforms: ${{ inputs.arch }}
          tags: ${{ inputs.build-cache-name }}
          labels: ${{ inputs.labels }}
          outputs: ${{ inputs.push && 'type=registry' || 'type=oci,dest=/tmp/image.tar' }}
          cache-from: type=gha,scope=${{ steps.generate-cache-scope.outputs.cache-scope }}
          cache-to: type=gha,scope=${{ steps.generate-cache-scope.outputs.cache-scope }},mode=max
